server:
  port: 8080

topicos:
  task:
      topic: "task.topic.v1"

spring:
  application:
    name: to.do.list
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3390/db_to_do_list?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
    username: mysqluser
    password: mysqlpw
    show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer